# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Android CI/CD
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-22.04
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
 
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      # with:
        # api-level: 30 # 根据项目需要设置API级别
        # build-tools-version: 30.0.3 # 根据项目需要设置Build Tools版本
 
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
 
    - name: Build with Gradle
      run: ./gradlew assembleRelease
 
    # 可选步骤：运行测试
    # - name: Run tests
    #   run: ./gradlew test
 
    # 可选步骤：上传APK到GitHub Releases（需要配置GITHUB_TOKEN）
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
 
    # 如果要自动发布到Google Play Store，你需要使用Google Play Publisher API和相应的GitHub Action
    # 注意：这需要配置服务帐户密钥和其他敏感信息，通常通过GitHub Secrets管理
 
# 注意：如果你打算上传APK到GitHub Releases或发布到Google Play Store，
# 你需要确保在仓库的Secrets中配置了必要的令牌和密钥。
# 例如，对于GitHub Releases，你可能需要配置GITHUB_TOKEN。
# 对于Google Play Store，你需要配置如GOOGLE_PLAY_SERVICE_ACCOUNT_KEY等。
